apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    env: dev
    app: tomcat
    tier: backend
    owner: ArtemieFliostor
spec:
  containers:
    - name: tomcat
      image: tomcat:8.5.38
      ports:
        - containerPort: 8080